In [1]:
import numpy as np

# Datos de entrenamiento
X = np.array([
    [0,1,0],   # centrado
    [1,0,0],   # linea izquierda
    [0,0,1]    # linea derecha
])

Y = np.array([
    [1,1],     # recto
    [0.2,1],   # girar izquierda
    [1,0.2]    # girar derecha
])

# arquitectura
input_size = 3
hidden_size = 4
output_size = 2

# inicializar pesos
np.random.seed(1)

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1,hidden_size))

W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1,output_size))


# función sigmoide
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_deriv(x):
    return x*(1-x)

# entrenamiento
lr = 0.1
epochs = 10000

for epoch in range(epochs):

    # forward
    z1 = np.dot(X,W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1,W2) + b2
    output = sigmoid(z2)

    # error
    error = Y - output

    # backprop
    d_output = error * sigmoid_deriv(output)

    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_deriv(a1)

    # actualizar pesos
    W2 += a1.T.dot(d_output) * lr
    b2 += np.sum(d_output,axis=0,keepdims=True) * lr

    W1 += X.T.dot(d_hidden) * lr
    b1 += np.sum(d_hidden,axis=0,keepdims=True) * lr


# mostrar pesos
print("\nPesos capa entrada -> oculta (W1)")
print(W1)

print("\nBias capa oculta")
print(b1)

print("\nPesos capa oculta -> salida (W2)")
print(W2)

print("\nBias salida")
print(b2)


Pesos capa entrada -> oculta (W1)
[[ 2.7289895  -2.36869016 -2.40623201 -0.59948909]
 [ 0.21865876 -2.42917783  2.68046307  0.72704245]
 [-0.84604535  1.78773994  2.23728403 -2.9365016 ]]

Bias capa oculta
[[-0.70718917  0.15253744 -0.16723285  1.08536798]]

Pesos capa oculta -> salida (W2)
[[-2.40325059  1.88833178]
 [ 1.38386013 -3.38311304]
 [ 4.57444158 -0.77741236]
 [ 0.4393316   3.13515532]]

Bias salida
[[0.01934851 1.51895807]]
